project:
  type: website
  output-dir: docs
  preview: 
    port: 1200
    browser: true

website:
  title: "Ocean Acidification"
  back-to-top-navigation: true
  search: true
  page-footer: |
    ![](/assets/logos/soest_logo.png){width=25%}&nbsp;&nbsp;
    ![](/assets/logos/nrem_logo.png){width=15%}&nbsp;&nbsp;&nbsp;&nbsp;
    ![](/assets/logos/uh_logo.png){width=15%}
    ![](/assets/logos/oap_logo.png){width=38%} 
        
format:
  html:
    theme: litera
    page-layout: full
    link-external-newwindow: true
    smooth-scroll: true

execute:
  message: false
  warning: false
  echo: true